### PR TITLE
Fix redirect from /docs, update README.md

### PR DESCRIPTION
**Pull request by runk**

### CODE REVIEW

**Comment by jdalton** [comment]
Thanks but I'm using https://www.netlify.com/docs/redirects.

**Comment by runk** [comment]
Any plans to fix https://lodash.com/docs?

**Comment by jdalton** [comment]
Sure. As I said I'm using netlify and have created the [_redirects](https://github.com/lodash/lodash.github.io/blob/master/_redirects) file. It's just not taking for some reason.

**Comment by runk** [comment]
Nice one!. Question - do you even need `group: :jekyll_plugins` in Gemfile if you don't load them in `_config.yml`?

**Comment by jdalton** [comment]
I have no idea. I'm not a ruby user so I'm just mimicking the install instructions:
https://github.com/github/pages-gem#usage

**Comment by jdalton** [comment]
See https://jekyllrb.com/docs/plugins/#commands.

**Pull request closed without merging**
