### PR TITLE
Add files.

### PR DESCRIPTION
**Pull request by d10**

### CODE REVIEW

**Comment by jdalton** [comment]
Hold off @d10. I'd like the initial commit to come from https://github.com/lodash/lodash/pull/1265.

**Comment by jdalton** [comment]
@InstyleVII

**Comment by d10** [comment]
Sure, I can wait on it. Let’s leave this for review first ;)

**Comment by jdalton** [comment]
Clayton can review this for tweaks but I see no need in having both. Let's close this for now.

**Pull request closed without merging**
