### PR TITLE
Lodash.com v2.0

### PR DESCRIPTION
**Pull request by zackhall**
The new lodash.com website!

To test out the website you can clone the repo locally, and then

1 – Install github-pages gem.

```
gem install github-pages
```

2 – Clone the repo locally.
3 – Build & run from repo dir.
```
jekyll build
jekyll serve --watch
```

### CODE REVIEW

**Comment by jfmengels** [comment]
Woohoo! :tada:

**Comment by demoneaux** [comment]
Really great, especially the new design by @veksen! Will try out the new design and give feedback :)

**Comment by zackhall** [comment]
image

**Comment by veksen** [comment]
Woo can't wait to see this in action, especially the docs

**Comment by veksen** [comment]
I'll do a PR to fix a few things, otherwise really nice job, it's nice to see it in action :)

**Pull request merged**
