### PR TITLE
make the text scaling less drastic at <1200px (14px body)

### PR DESCRIPTION
**Pull request by veksen**
I'm open to suggestions, but I think it's an improvement over the (way too small) ~12px we had previously.

### CODE REVIEW

**Comment by jdalton** [comment]
I think the default font size is 16px? Should [we be explict](http://www.standardista.com/px-to-rem-conversion-if-root-font-size-is-16px/) about it though?

```css
:root {
font-size: 16px;
}
```

**Comment by veksen** [comment]
@jdalton The default size is 16px by default, but is (right now) set to `0.75rem` on a media query smaller than 1200px, which makes it 12px (16*0.75).

There are various ways to handle a default font size, while scaling with `em`/`rem`, but the practice I follow and recommend is setting the font size to 16px on the `html`, and then setting a `rem` on the `body`.

**Comment by jdalton** [comment]
> There are various ways to handle a default font size, while scaling with em/rem, but the practice I follow and recommend is setting the font size to 16px on the html, and then setting a rem on the body.

PR or commit please :)

**Comment by veksen** [comment]
@jdalton I'd still like @zackhall opinion. There is currently a mix usage of `em` and `rem` through the css, and the html is currently set at 100%. Thoughts?

**Comment by calvinf** [comment]
Please consider using a darker font color for the method names in the left nav.  I'm not sure the current color meets accessibility contrast guidelines, but I haven't used a tool yet to check this.

**Comment by jdalton** [comment]
The font size issue can be tackled in the PR but contrast tweaks should be a separate one.
I used [contrast-ratio](http://leaverou.github.io/contrast-ratio/) and things weren't horrible.

**Comment by calvinf** [comment]
For this selector: `html.docs .toc-container ul li a`

> "Passes AA for large text (above 18pt or bold above 14pt)".  Increasing the size will help, but not get it all the way.

* [#797979-on-white](http://leaverou.github.io/contrast-ratio/#%23797979-on-white)

To pass WCAG AA for all sizes, I'd recommend changing the color to `#777`.

* [#777-on-white](http://leaverou.github.io/contrast-ratio/#%23777-on-white)

**Comment by veksen** [comment]
@calvinf Yes, I was just looking at constrasts. Bumping the contrast just a tiny bit would meet AAA on the body. I'll PR for the menu and check for the rest of the site/docs.

**Comment by calvinf** [comment]
@veksen sounds good, thanks!

**Comment by zackhall** [comment]
RE: 

> There is currently a mix usage of em and rem through the css, and the html is currently set at 100%. Thoughts?

Yeah... I went through a pass on the CSS and mostly just asked myself the question, "Should this scale with the document or should this scale with its parent?" 

But even so I still ended with a mix of `rem` and `em`. I could use some more practice or guidelines on what the best use of the two is. 

> the practice I follow and recommend is setting the font size to 16px on the html, and then setting a rem on the body.

Yeah, I like that a lot!

**Comment by jdalton** [comment]
> the practice I follow and recommend is setting the font size to 16px on the html, and then setting a rem on the body.
>>Yeah, I like that a lot!

Woot! @veksen could you tackle the PR for default font size jazz?

**Pull request merged**
